"""
BIS Sahayak — Chat Session & Message Models
Phase 5: Database Schema

Tables:
  - chat_sessions  : A conversation session (groups multiple messages)
  - chat_messages  : Individual messages within a session
"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, String, Text, func
from sqlalchemy.dialects.postgresql import JSON, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


class ChatSession(Base):
    """
    A chat session groups a series of messages in a single conversation.

    `mode` distinguishes different assistant modes, e.g.:
      - "standard_lookup"  : search a specific IS standard
      - "general_query"    : general BIS question
    """

    __tablename__ = "chat_sessions"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=func.gen_random_uuid(),
    )

    # Assistant mode for this session
    mode: Mapped[str] = mapped_column(String, nullable=False)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    # One session has many messages
    messages: Mapped[list["ChatMessage"]] = relationship(
        "ChatMessage",
        back_populates="session",
        cascade="all, delete-orphan",
        passive_deletes=True,
        order_by="ChatMessage.created_at",
    )

    def __repr__(self) -> str:
        return f"<ChatSession id={self.id} mode={self.mode!r}>"


class ChatMessage(Base):
    """
    A single message inside a ChatSession.

    `role` follows the LLM convention:
      - "user"      : message sent by the user
      - "assistant" : message generated by BIS Sahayak
      - "system"    : system prompt (if stored)

    `citations` is a JSONB array of source references, e.g.:
      [
        {"standard_number": "IS 14543", "clause": "4.2", "page": 12},
        ...
      ]
    This is nullable — user messages and system messages have no citations.
    """

    __tablename__ = "chat_messages"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=func.gen_random_uuid(),
    )

    session_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("chat_sessions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # "user" | "assistant" | "system"
    role: Mapped[str] = mapped_column(String, nullable=False)

    # Full text of the message
    content: Mapped[str] = mapped_column(Text, nullable=False)

    # Optional JSON array of cited document chunks
    citations: Mapped[dict | list | None] = mapped_column(JSON, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    # Many messages belong to one session
    session: Mapped["ChatSession"] = relationship(
        "ChatSession", back_populates="messages"
    )

    def __repr__(self) -> str:
        return (
            f"<ChatMessage id={self.id} "
            f"session_id={self.session_id} "
            f"role={self.role!r}>"
        )
